# Generated by Django 3.2.8 on 2021-10-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='puntos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
