# Generated by Django 3.2.8 on 2021-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_userprofile_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(0, 'novato'), (1, 'sabiondo'), (2, 'estrella')], default=0),
        ),
    ]
