# Generated by Django 3.2.8 on 2021-11-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
