# Generated by Django 3.2.8 on 2021-10-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoLecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(db_column='image_url', upload_to='images/lecciones')),
            ],
        ),
        migrations.CreateModel(
            name='RecursosHasLecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecursosHasLecciones_leccion', to='juego.leccion')),
                ('recurso_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecursosHasLecciones_recurso_leccion', to='recursos.recursolecciones')),
            ],
        ),
    ]
