# Generated by Django 3.2.8 on 2021-10-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_historial_nivelesactividades_opciones_opcionesri_reconocimientoimagenes_trivia'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='image_url', upload_to='images/trivias')),
                ('trivia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RecursoTrivia_trivia', to='juego.trivia')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOpcionRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='image_url', upload_to='images/opciones-ri')),
                ('opcion_ri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RecursoOpcionRI_opcionri', to='juego.opcionesri')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='image_url', upload_to='images/opciones')),
                ('opcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RecursoOpcion_opcion', to='juego.opciones')),
            ],
        ),
    ]
