# Generated by Django 3.2.8 on 2021-11-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_leccion_resumen'),
        ('recursos', '0002_recursoopcion_recursoopcionri_recursotrivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursolecciones',
            name='leccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='RecursosHasLecciones_leccion', to='juego.leccion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecursosHasLecciones',
        ),
    ]
