# Generated by Django 3.2.8 on 2021-11-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20211110_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecursoOpcionRI',
        ),
    ]
