# Generated by Django 3.2.8 on 2021-10-21 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelesActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('dificultad', models.PositiveSmallIntegerField(choices=[(0, 'principiante'), (1, 'experimentado'), (2, 'profesional')], default=0)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NivelesActividades_leccion', to='juego.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trivia_actividades', to='juego.nivelesactividades')),
            ],
        ),
        migrations.CreateModel(
            name='ReconocimientoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReconocimientoImagenes_actividad', to='juego.nivelesactividades')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=200)),
                ('opcion_correcta', models.BooleanField(default=False)),
                ('reconocimiento_imagenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpcionesRI_reconocimientoimagenes', to='juego.reconocimientoimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=200)),
                ('opcion_correcta', models.BooleanField(default=False)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opciones_trivia', to='juego.trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('like', models.BooleanField(default=False)),
                ('niveles_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historial_nivelesactividades', to='juego.nivelesactividades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historial_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
