# Generated by Django 3.2.8 on 2021-11-10 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_delete_recursoopcionri'),
        ('juego', '0005_leccion_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionesri',
            name='reconocimiento_imagenes',
        ),
        migrations.RemoveField(
            model_name='reconocimientoimagenes',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='niveles_actividades',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='actividad',
        ),
        migrations.AddField(
            model_name='historial',
            name='trivia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Historial_trivia', to='juego.trivia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='instrucciones',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='leccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Trivia_leccion', to='juego.leccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trivia',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'preguntas'), (1, 'imagenes')], default=0),
        ),
        migrations.DeleteModel(
            name='NivelesActividades',
        ),
        migrations.DeleteModel(
            name='OpcionesRI',
        ),
        migrations.DeleteModel(
            name='ReconocimientoImagenes',
        ),
    ]
