# Generated by Django 3.2.8 on 2021-11-10 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_auto_20211110_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
