# Generated by Django 3.2.8 on 2021-11-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_historial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
