# Generated by Django 3.2.8 on 2021-11-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_alter_historial_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=500)),
                ('razon', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
