# Generated by Django 3.2.8 on 2021-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0009_logros'),
    ]

    operations = [
        migrations.AddField(
            model_name='logros',
            name='icon',
            field=models.FileField(db_column='image_url', default='', upload_to='images/logros'),
            preserve_default=False,
        ),
    ]
